services:
  - type: web
    name: matchday-backend
    runtime: java
    plan: free
    buildCommand: "bash ./mvnw clean package -DskipTests"
    startCommand: "java -jar target/matchday-backend-0.0.1-SNAPSHOT.jar"
    healthCheckPath: /health
    envVars:
      - key: JAVA_VERSION
        value: 21
      - key: MONGODB_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false
