spring.application.name=matchday-backend
server.port=${PORT:8080}
spring.data.mongodb.uri=mongodb+srv://rajverse-dev:rajverse126@cluster1.ufwpu4q.mongodb.net/matchdata_ai?appName=Cluster1

spring.jackson.serialization.indent_output=true

# Gemini AI configuration
gemini.api.key=${GEMINI_API_KEY:}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta
gemini.model=gemini-3-flash-preview
