spring.application.name=matchday-backend
server.port=${PORT:8080}
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/matchdata_ai}

spring.jackson.serialization.indent_output=true

# Gemini AI configuration
gemini.api.key=${GEMINI_API_KEY:}

gemini.api.url=https://generativelanguage.googleapis.com/v1beta

gemini.model=gemini-3-flash-preview
